using Entities.Concrete;
using Entities.Enums;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Repositories.Configurations.Extensions
{
    public static class UserConfigurationExtensions
    {
        public static void AddSeedData(this EntityTypeBuilder<User> builder)
        {
            //  Add Admin
            builder.HasData(new User
            {
                Id = 3,
                AimId = 1,
                FirstName = "Admin",
                LastName = "Admin",
                Email = "admin",
                Height = 1.80,
                Weight = 80,
                UserStatus = Entities.Enums.UserStatus.Active,
                UserAccess = UserAccess.Admin,
                UserVerification = null,
                #region password

                PasswordSalt = new byte[] {
                    218,
                    189,
                    128,
                    231,
                    168,
                    98 ,
                    232,
                    98 ,
                    139,
                    76 ,
                    236,
                    125,
                    11 ,
                    48 ,
                    125,
                    153,
                    166,
                    3  ,
                    24 ,
                    232,
                    92 ,
                    172,
                    60 ,
                    249,
                    240,
                    145,
                    203,
                    137,
                    156,
                    151,
                    225,
                    241,
                    181,
                    73 ,
                    180,
                    119,
                    86 ,
                    175,
                    146,
                    71 ,
                    27 ,
                    159,
                    156,
                    177,
                    31 ,
                    106,
                    30 ,
                    172,
                    1  ,
                    131,
                    212,
                    1  ,
                    222,
                    200,
                    24 ,
                    155,
                    128,
                    130,
                    141,
                    187,
                    154,
                    166,
                    193,
                    212,
                    166,
                    251,
                    231,
                    198,
                    99 ,
                    113,
                    142,
                    93 ,
                    168,
                    187,
                    54 ,
                    113,
                    122,
                    216,
                    169,
                    54 ,
                    179,
                    67 ,
                    58 ,
                    64 ,
                    138,
                    58 ,
                    87 ,
                    249,
                    194,
                    9  ,
                    159,
                    250,
                    227,
                    177,
                    172,
                    49 ,
                    93 ,
                    8  ,
                    170,
                    199,
                    201,
                    111,
                    240,
                    22 ,
                    144,
                    154,
                    154,
                    219,
                    81 ,
                    255,
                    69 ,
                    3  ,
                    78 ,
                    67 ,
                    210,
                    204,
                    181,
                    236,
                    119,
                    170,
                    44 ,
                    71 ,
                    39 ,
                    101,
                    142,
                    174,
                    201,
                    28

                },
                PasswordHash = new byte[] {
                    108,
                    201,
                    165,
                    162,
                    112,
                    59 ,
                    180,
                    38 ,
                    187,
                    6  ,
                    81 ,
                    121,
                    8  ,
                    251,
                    225,
                    102,
                    89 ,
                    166,
                    151,
                    220,
                    72 ,
                    221,
                    161,
                    222,
                    194,
                    58 ,
                    78 ,
                    214,
                    35 ,
                    54 ,
                    234,
                    34 ,
                    98 ,
                    89 ,
                    162,
                    119,
                    0  ,
                    116,
                    87 ,
                    132,
                    75 ,
                    27 ,
                    15 ,
                    7  ,
                    137,
                    46 ,
                    249,
                    85 ,
                    121,
                    122,
                    15 ,
                    201,
                    153,
                    108,
                    253,
                    134,
                    202,
                    214,
                    171,
                    3  ,
                    100,
                    171,
                    142,
                    51

                }
                #endregion

            });
        }
    }
}
